### ISSUE TITLE
construction/submit endpoint locks db

### ISSUE THREAD

**Issue by barbaraliau** [celo-org/rosetta#126] opened 2020-12-03 21:55 UTC
Last working commit is `5038f0593be80ed867f557fb2974d6b8f9402a32`

Changes after that commit cause `/construction/submit` to fail. All other methods tested (polling, constructing, signing) work.

Error:
```
{
    "code": 500,
    "message": "Internal server error",
    "retriable": false,
    "details": {
        "context": "database is locked:[err database is locked]"
    }
}
```

* Breaking change introduced sometime after #111
* Possibly moving to the Construction API approach broke `construction/submit` and is no longer backwards compatible

**Notes on initial debugging:**
- using the updated Construction API (and not the older version in the release) would have caused an error due to a change in expected request encoding, but it should have caused a different error; unclear why this particular error was thrown
- `database is locked:[err database is locked]` looks like a sqlite db error and not a LevelDB error, indicating it's likely a problem with `rosetta.db` (rosetta's internal SQLite db) and not the geth db that's locking for some reason

**Comment by aslawson** [comment] 2021-02-08 16:26
@eelanagaraj is this fixed already?

**Comment by eelanagaraj** [comment] 2021-02-08 16:36
@aslawson we haven't been able to repro but think it had to do with the API being used assuming an incorrect spec version -- will slack you more details

**Comment by aslawson** [comment] 2021-02-09 21:26
closing for now since cannot reproduce. can re-open if it occurs again

**Closed by aslawson** 2021-02-09 21:26 UTC
Labels: bug, devX
